### PR TITLE
change in cursor:pointer in style.css

### PR DESCRIPTION
**Pull request by rohir1132yadav**
#148 
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)#148

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK (if applicable)

### CODE REVIEW

**Comment by Dev-tanay** [comment]
Please attach a video sample of the changes

**Comment by Kartikk1820** [comment]
Assign this issue to me I am from GSSoC'24 . I am good in CSS I can change the cursor to pointer

**Comment by angshuman-web** [comment]
The current cursor does not change when hovering over the cube. Change in the cursor style when hovering over the Cube to something more distinct will help the user to differentiate. Please assign me this I want to fix this issue.

**Comment by Soujanya2004** [comment]
hi, I have been following your project and would love to contribute, please assign me the issue.

**Pull request merged**
