### PR TITLE
Background theme change

### PR DESCRIPTION
**Pull request by ayushkrrana**
# Description
Changes background theme with some animation 

Fixes:  #(issue no.)

#196 

## Type of change
Add background theme

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK (if applicable)
[

https://github.com/Dev-tanay/Rubik-Cube/assets/160728166/097ede30-c3ce-402c-8f23-0d49d16a7e59

](url)

### CODE REVIEW

**Comment by ayushkrrana** [comment]
@Dev-tanay Please see
Thank you

**Comment by ayushkrrana** [comment]
@Dev-tanay Please check

**Comment by Dev-tanay** [comment]
Bro, it's not looking that much attractive.
you can try 2d animated background or simple background

**Comment by ayushkrrana** [comment]
> Bro, it's not looking that much attractive. you can try 2d animated background or simple background

ok i will delete this pr and generate another pr for this

**Pull request closed without merging**
