### PR TITLE
Contributor's Logo and Addition of Preloader

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #210
issue #211 

# Description

Addition contributor's Logo and Preloader.

Fixes:  #210  and #211 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK (if applicable)

image

https://github.com/Dev-tanay/Rubik-Cube/assets/154777864/25cfca1b-c614-42b8-85b5-8e08f549e097

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the PR

**Comment by Dev-tanay** [comment]
Changing the Preloader is possible with a cube?

**Comment by Anjaliavv51** [comment]
Yes sure

**Comment by Anjaliavv51** [comment]
@Dev-tanay i made the changes and also this PR containes both issues of #210 and #211
i think if possible u can add level 2 label to the PR #214

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the changes

**Comment by Anjaliavv51** [comment]
@Dev-tanay

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the Pr

**Comment by Dev-tanay** [comment]
Please attach a video @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Dev-tanay please see the above attached videos

**Comment by Anjaliavv51** [comment]
@Dev-tanay please see the attached video

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the PR

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the PR

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the changes
@Dev-tanay i made the changes and also this PR containes both issues of #210 and #211
i think if possible u can add level 2 label to the PR #214

**Comment by Anjaliavv51** [comment]
@Dev-tanay please review the PR

**Comment by Anjaliavv51** [comment]
@Dev-tanay please add level 2 label as it contains both , addition of Preloader and contributors logo

**Comment by Anjaliavv51** [comment]
@Dev-tanay please add level 2 label as it contains both , addition of Preloader and contributors logo

**Comment by Anjaliavv51** [comment]
@Dev-tanay please add level 2 label as it contains both , addition of Preloader and contributors logo

**Comment by Anjaliavv51** [comment]
@Dev-tanay please add level 2 label as it contains both , addition of Preloader and contributors logo

**Pull request merged**
